Time	SQL
	ALTER TABLE CAD_PRODUTOS ADD CONSTRAINT FK_IDCADCATEGORIA FOREIGN KEY (ID_CADCATEGORIA)
  REFERENCES CAD_CATEGORIAS (ID_CADCATEGORIA)
	INSERT INTO CAD_PRODUTOS (DESCRICAO_CADPRODUTOS, VALOR_CADPRODUTO, ID_CADCATEGORIAS)
        VALUES ('MOUSE', '30',1)
	INSERT INTO CAD_PRODUTOS (DESCRICAO_CADPRODUTOS, VALOR_CADPRODUTO, ID_CADCATEGORIAS)
        VALUES ('MOUSE', '30',1)
	INSERT INTO CAD_PRODUTOS (DESCRICAO_CADPRODUTOS, VALOR_CADPRODUTO, ID_CADCATEGORIAS),
        VALUES ('MOUSE', '30',1)
	INSERT INTO CAD_PRODUTOS (DESCRICAO_CADPRODUTOS, VALOR_CADPRODUTO, ID_CADCATEGORIA),
        VALUES ('MOUSE', '30',1)
	INSERT INTO CAD_PRODUTOS (DESCRICAO_CADPRODUTOS, VALOR_CADPRODUTO, ID_CADCATEGORIA)
        VALUES ('MOUSE', '30',1)
	INSERT INTO CAD_PRODUTOS (DESCRICAO_CADPRODUTOS, VALOR_CADPRODUTO, ID_CADCATEGORIA)
        VALUES ('MOUSE', '30',1)
	INSERT INTO CAD_PRODUTOS (DESCRICAO_CADPRODUTO, VALOR_CADPRODUTO, ID_CADCATEGORIA),
        VALUES ('MOUSE', '30',1)
INSERT INTO CAD_PRODUTOS (DESCRICAO_CADPRODUTO, VALOR_CADPRODUTO, ID_CADCATEGORIA)
        VALUES ('MOUSE', '30',1)
select CAD_CLIENTES
	select CAD_CLIENTES
select FROM CAD_CLIENTES
	check the manual that corresponds to your MariaDB server version for the right syntax to use near '* FROM CAD_CLIENTES LIMIT 0. 1000)' at line 1 0.000 sec
	insert INTO CAD_CLIENTES (NOME_CAD_CLIENTE ,EMAIL_CADCLIENT )
                   VALUES ('MARIA DE SOUZA', 'MARIA .SOUZA@PROWAY.COM.BR')
	select (* FROM CAD_CLIENTES LIMIT 0. 1000)
	INSERT INTO CAD_CLIENTE (NOME_CADCLIENTE) values('JUCA DA SILVA')
	describe CAD_CLIENTE
	SHOW TABLES
	DESCRIBE CAD_PRODUTOS
	CREATE TABLE CAD_ITENSVENDA(
 ID_CADITEMVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 ID_CADVENDA INT NOT NULL,
 ID_CADPRODUTO INT NOT NULL)
	CREATE TABLE CAD_ITENS VENDA(
 ID_CADITEMVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 ID_CADVENDA INT NOT NULL,
 ID_CADPRODUTO INT NOT NULL,)
	CREATE TABLE CAD_VENDAS ( ID_CADVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT, DATA_CADVENDA DATE NOT NULL,   ID_CADCLIENTE INT NOT NULL )
 DROP TABLE CAD_VENDAS
	CREATE TABLE CAD_VENDAS ( ID_CADVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT, DATA_CADVENDA DATE NOT NULL, 
                  ID_CADPRODUTO INT NOT NULL, ID_CADCLIENTE INT NOT NULL )
 DROP TABLE CAD_VENDAS
	CREATE TABLE CAD_VENDAS ( ID_CADVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT, DATA_CADVENDA DATE NOT NULL, 
 ID_CADPRODUTO INT NOT NULL, ID_CADCLIENTE INT NOT NULL )
 DROP TABLE CAD_VENDAS
	CREATE TABLE CAD_VENDAS ( ID_CADVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT, DATA_CADVENDA DATE NOT NULL, 
 ID_CADPRODUTO INT NOT NULL, ID_CADCLIENTE INT NOT NULL )
	SHOW TABLES
10:55:27	DROP TABLE CAD_VENDAS
10:53:56	CREATE TABLE CAD_VENDAS (
 ID_CADVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 DATA_CADVENDA DATE NOT NULL,
 ID_CADPRODUTO INT NOT NULL,
 ID_CADCLIENTE INT NOT NULL )
SHOW TABLES
	CREATE TABLE CAD_CLIENTE (
 ID_CADCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 NOME_CADCLIENTE VARCHAR(50) NOT NULL,
 EMAIL_CADCLIENTE VARCHAR (100)
 )
	CREATE TABLE CAD_CATEGORIAS(  ID_CADCATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,  
    DESCRICAO_CADCATEGORIA VARCHAR(50) NOT NULL )
	CREATE TABLE CAD_PRODUTOS (
 ID_CADPRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 DESCRICAO_CADPRODUTO VARCHAR (100) NOT NULL,
 ID_CATEGORIA INT NOT NULL
 )
	CREATE TABLE CAD_CATEGORIAS(
  ID_CADCATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
     DESCRICAO_CAD CATEGORIA VARCHAR(50) NOT NULL
 )
	USE loja
	CREATE TABLE CAD_CATEGORIAS(
  ID_CADCATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
     DESCRICAO_CAD CATEGORIA VARCHAR(50) NOT NULL
 )
	CREATE DATABASE loja
	CREATE DATABASE loja



